local cmd = vim.api.nvim_create_user_command
cmd("FzfKastenDaily", function()
	require("fzfkasten").goto_daily()
end, { desc = "Fzfkasten: Daily Note" })
cmd("FzfKastenWeekly", function()
	require("fzfkasten").goto_weekly()
end, { desc = "Fzfkasten: Weekly Note" })
cmd("FzfKastenSearch", function()
	require("fzfkasten").find_notes()
end, { desc = "Fzfkasten: Search Notes" })
cmd("FzfKastenTags", function()
	require("fzfkasten").search_tags()
end, { desc = "Fzfkasten: Search Tags" })
cmd("FzfKastenInsert", function()
	require("fzfkasten").insert_link()
end, { desc = "Fzfkasten: Insert Link" })
