local cmd = vim.api.nvim_create_user_command
cmd("FzfKastenDaily", function() require('fzfkasten').goto_daily() end, { desc = "Fzfkasten: Daily Note" })
cmd("FzfKastenWeekly", function() require('fzfkasten').goto_weekly() end, { desc = "Fzfkasten: Weekly Note" })
cmd("FzfKastenFindNotes", function() require('fzfkasten').find_notes() end, { desc = "Fzfkasten: Find notes" })
cmd("FzfKastenTags", function() require('fzfkasten').search_tags() end, { desc = "Fzfkasten: Search Tags (all occurrences)" })
cmd("FzfKastenSearchByTag", function() require('fzfkasten').search_by_tag() end, { desc = "Fzfkasten: Filter notes by tag" })
cmd("FzfKastenInsert", function() require('fzfkasten').insert_link() end, { desc = "Fzfkasten: Insert Link" })
cmd("FzfKastenSearchContent", function() require('fzfkasten').search_content() end, { desc = "Fzfkasten: Search note content" })
cmd("FzfKastenNewNote", function() require('fzfkasten').new_note() end, { desc = "Fzfkasten: Create a new note" })
cmd("FzfKastenRenameNote", function() require('fzfkasten').rename_note() end, { desc = "Fzfkasten: Rename current note and update links" })
cmd("FzfKastenPanel", function() require('fzfkasten').panel() end, { desc = "Fzfkasten: Panel" })
cmd("FzfKastenFollowLink", function() require('fzfkasten').follow_link() end, { desc = "Fzfkasten: Follow Link" })
cmd("FzfKastenShowBacklinks", function() require('fzfkasten').show_backlinks() end, { desc = "Fzfkasten: Show Backlinks" })
cmd("FzfKastenFindDailyNotes", function() require('fzfkasten').find_daily_notes() end, { desc = "Fzfkasten: Find Daily Notes" })
cmd("FzfKastenFindWeeklyNotes", function() require('fzfkasten').find_weekly_notes() end, { desc = "Fzfkasten: Find Weekly Notes" })
cmd("FzfKastenClaudeSendBuffer", function() require('fzfkasten').claude_send_buffer() end, { desc = "Fzfkasten: Send note to Claude" })
cmd("FzfKastenClaudeSendSelection", function() require('fzfkasten').claude_send_selection() end, { range = true, desc = "Fzfkasten: Send selection to Claude" })
cmd("FzfKastenClaudeToggle", function() require('fzfkasten').claude_toggle() end, { desc = "Fzfkasten: Toggle Claude terminal" })